### ISSUE TITLE
Lithium v3.0 - Features

### ISSUE THREAD

**Issue by hugoqribeiro** [PrimaveraDeveloper/lithium#8]
**Version 3.0** of the Lithium SDK (and Hydrogen, etc.) **could** include the following features:

**Service Designer**

- New domain entity to model configuration options.

**Solution Templates**

- Rename WebApi project to Server. This would clarify solutions where the server has a back-office.
- New server project to hold shared classes (e.g. models, constants, etc.). This would simplify solutions where "infrastructure" (additional projects for more complex architectures) is needed.

**Hydrogen**

- (...)

**Comment by PedroMGMendes** [comment]
**Microservice Chassis Improvements (SDK)**

- Upgrade .Net Core 3.1 projects to .NET 5.0 
- CQRS code on controllers
- Option to gen Clean Arch projects(csproj's)
- Option to Generate gRPC controllers

**Hydrogen**

- Model to return http error responses as defined in https://tools.ietf.org/html/rfc7807#section-3

**NTH**

- Out-of-the-box Storage Abstraction Solution ("Easy to use")
- Basic UI

**Comment by ibbgomes** [comment]
### Hydrogen

**Design Time:**

- Migrate to `Microsoft.CodeAnalysis.NetAnalyzers`, since `Microsoft.CodeAnalysis.FxCopAnalyzers` is officially [deprecated](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers).

**Webhooks:**

- Webhooks could support an event-driven strategy.

**Event Bus:**

- The Azure implementation could support the [claim-check](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check) pattern.

**Comment by hugoqribeiro** [comment]
> ### Hydrogen
> **Design Time:**
> 
> * Migrate to `Microsoft.CodeAnalysis.NetAnalyzers`, since `Microsoft.CodeAnalysis.FxCopAnalyzers` is officially [deprecated](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers).

Upgraded 2 or 3 weeks ago... ;)

> 
> **Webhooks:**
> 
> * Webhooks could support an event-driven strategy.

Please ellaborate...

**Comment by hugoqribeiro** [comment]
> * Upgrade .Net Core 3.1 projects to .NET 5.0

Will happen on 2.0.

**Comment by PedroMGMendes** [comment]
The Lithium FW has come a long way and improved greatly overtime, I'd reckon it fulfills it's main target at about 70%. 
After thinking a bit more about where this is heading here's a list of more abstract goals of what is missing and should be considered for vNext:


**V3**
 - Easier storage solution -> storage done right is hard...and there's no time for it :) we need to abstract sdk users from this.
 - Do we want to enforce an arch for the infrastructure part?  **yes** -> using clean arch "à lá juice"	
 - Custom code on WebApi proj should be reduced to the max - use the mediator component on hydrogen plus CQRS pattern to achieve this goal -> similar approach used on "juice" combined with the previous point about arch.

**V4**
 - UI

**V5**
- Process designer for micro services composability ( creating new micro services using other micro services possibly using taskbox as a way to help achieve this)

Some interesting technical objectives to consider would be:
- Take advantage of features in C# 9.0
- Source Generators
- Deployment is always evolving and requiring work and always a challenge (k8 is still a long way off

**Comment by ibbgomes** [comment]
> > **Webhooks:**
> > 
> > * Webhooks could support an event-driven strategy.
> 
> Please ellaborate...

Sorry, my suggestion was somewhat misleading, since webhooks are indeed event-driven.

The current webhooks solution could, in theory, support a strategy where a message broker (e.g. event bus) would act as a mediator between publish and subscribe operations. In my view, this strategy would provide several advantages, such as:
- Space and time decoupling would yield true asynchronous behavior;
- The message broker storage and management features could improve robustness. For example, failed events could be stored in a dedicated queue for subsequent analysis and processing;
- Improved scalability. An event could trigger a serverless function that would ping the corresponding HTTP callback endpoint;
- More support for extensibility. The message broker can be integrated with several other components.

I don’t know the implementation implications of adding such a strategy, and it would be certainly more complex than the current one, but it’s a suggestion.

**Comment by hugoqribeiro** [comment]
Consolidating [here](https://github.com/PrimaveraDeveloper/lithium/blob/master/future-work.md).

Discussion can continue here please.

**Comment by Kiril1512** [comment]
### Taskbox

Generate code for Taskbox dependency:
* Generate BackgroundService that is responsible to start the Taskbox;
* Generate AsyncTasks controllers;
* Generate Clustering controllers;
* Generate Task managers;
* Generate .Isspec configuration;
* Add possibility to define actions and triggers in the service designer;
* Generate extensions to add taskbox components (that are previously defined in the designer).

### Taskbox Clustering Client
Add taskbox clustering client when using taskbox. This will help monitor and manage async task from a client interface.
